export ZSH="$HOME/.oh-my-zsh"

# THEME
#ZSH_THEME="afowler" #normal
#ZSH_THEME="robbyrussell" # only show direct folder
ZSH_THEME="bira" # 2 line 

# PLUGINS
plugins=(git)

# OTHER
source $ZSH/oh-my-zsh.sh

alias clr="clear && "
alias stackid="stack exec -- ghcid -T :main"
alias sb="stack build"
alias sg="stack ghci" 
alias ownScript="chmod u+x"
alias gid="~/bin/gid.sh"
alias refreshZsh=". ~/.zshrc"

. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
